### ISSUE TITLE
Category edit field corrupted with multiple values

### ISSUE THREAD

**Issue by TonyGravagno** [abstractspoon/ToDoList_Resources#10]
When a single value is selected for category, it displays fine. When more than one field is selected, mouse away from the field to lose focus and something is displaying on top of the fields. Other fields do not appear to have this issue but a complete check hasn't been made.

![Category edit control](http://i198.photobucket.com/albums/aa83/CaptainStarbuck/Screenshots/ToDoList/150711125146_tmpimg_zpsjnb9rmyh.png)

**Comment by Pierre-de-la-Verre** [comment]
Maybe a side effect of Themes? I have "Win 7 Classic View" and no problems with display.

**Comment by TonyGravagno** [comment]
No but thanks. I use the default VS2010 theme but I've tried the others with no change.

**Comment by abstractspoon** [comment]
Thx Tony, this replicates a report someone else filed on CP.

As a related aside, we need to decide the minimum level of information required for a valid bug report.

At the very least this needs to include the OS version and whether or not themes are enabled in Windows, etc. and include a clear set of steps to reproduce.

Currently TDL is being supported on XP, Win7, Win8, Win8.1, Linux and soon Win10.

**Comment by abstractspoon** [comment]
Hi Tony

I'm not able to reproduce this yet on a VM running Win8 (not 8.1 AFAIK), so any further info would be appreciated.
![cat_bug](https://cloud.githubusercontent.com/assets/12944354/8645809/f5293900-298d-11e5-9142-dce686f66c4d.png)

**Comment by abstractspoon** [comment]
This issue was moved to abstractspoon/ToDoList_Wiki#3
