### ISSUE TITLE
HMS format truncates to HhMm

### ISSUE THREAD

**Issue by TonyGravagno** [abstractspoon/ToDoList_Resources#11]
**Tools > Preferences > User Interface > Tasklist Attributes> Date/Time Formatting >**
**"Display 'Estimated/Spent' times in HMS format"**

The fields actually look like 2h14m. There is no seconds value. When I see "HMS format" I think HH:MM:SS.

I looked into this option because I was thinking some project types might actually want timing down to the second. Then I thought the real goal was simply to show 1h30m rather than 1.5h.

So if seconds aren't a factor should the "S" be removed?

Or Is it a bug that seconds are not displayed?

To take this further, if a task is estimated at 50 hours, where 1 day = 8 hours and one week = 5 days, then the value displayed is "1w1d". So the hours get trimmed off here like seconds are trimmed above. And large hour values return values like 2y5m with days truncated.

So is it consistent and expected that the least significant units are removed? (They are not rounded.)

Is it assumed that as the values get larger that the details become less important - so 2y5m3d2h9m becomes ridiculous as a project estimate? If this is the case (and I'd agree), I'm wondering if the values should be rounded up rather than truncated. And does this same logic apply to time spent where actual time might be more significant than a rounded estimate?

**Comment by abstractspoon** [comment]
The whole point of this format was to hide insignificant  information only, and was probably a request from way back.

I also realise that HMS is not strictly correct but it still best describes what you are going to get.

I don't have a problem increasing the significant 'elements' to 3 but I don't feel it's very high priority.

**Comment by abstractspoon** [comment]
This issue was moved to abstractspoon/ToDoList_Wiki#2
