### ISSUE TITLE
Default for Due Time

### ISSUE THREAD

**Issue by TonyGravagno** [abstractspoon/ToDoList_Resources#12]
If not set, the Due Time is 11:59, meaning the task should be completed by the end of the Due Date. I'm thinking there would be value to having that value set in preferences. Someone working in an office generally doesn't have until midnight to complete a task - all tasks must be done by the end of the work day, maybe 5pm.

The value might be dependent on the task type. So for example if the Tag is set to "FedEx" to indicate the results of the task are going to be put into a package for pick up, then the Due Time might be set to 2pm if it's still the default value of 11:59 or 5pm.

**Comment by abstractspoon** [comment]
This issue was moved to abstractspoon/ToDoList_Wiki#1
