### ISSUE TITLE
PLEASE ONLY POST BUNDLED-RESOURCE-RELATED ISSUES HERE

### ISSUE THREAD

**Issue by abstractspoon** [abstractspoon/ToDoList_Resources#13]
Please post all ToDoList bug reports/feature requests/etc to the [ToDoList Issue Tracker](https://github.com/abstractspoon/ToDoList_Wiki/issues).

**Comment by TonyGravagno** [comment]
Dan, since the Resources repo has been more clearly defined as encompassing all resources, should this ticket maintain the title PLEASE ONLY POST TRANSLATION-RELATED ISSUES HERE ?

I'm thinking PLEASE ONLY POST ISSUES ABOUT FILES UNDER \RESOURCES HERE.

**Comment by abstractspoon** [comment]
Sure, I'll change it.

Have a good day.
