### ISSUE TITLE
Typos found in YourLanguage.csv

### ISSUE THREAD

**Issue by PatriceTorchet** [abstractspoon/ToDoList_Resources#14]
I checked YourLanguage.csv in Word's spell-checker, English UK dictionary.
it says:
2 'r' to occurrence
"Calculate next occurence" "" "label.1234"

"n" is missing in "Dynamically"
"Dyamically adjust the height of tasks to ensure full visibility" "" "checkbox.1040"

priveleges is writen "privileges"
"ToDoList was unable to install the 'outlook:' protocol handler.\n\nYou may need to run ToDoList with administrator priveleges to install the handler.\n\nOnce installed you can then revert to your original security settings." "" "text"

I am correction all Translations files right now

**Comment by Pierre-de-la-Verre** [comment]
Patrice
can it be closed?
