### ISSUE TITLE
Permanent "issue" to discuss unneeded / bogus strings in language files (don't close it!)

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [abstractspoon/ToDoList_Resources#22]
As discussed with Dan - this topic should be discussed and maintained, but NOT closed:

<del>20.08.2015: TDL 7.0, Textstrings for the tooltips</del>
>    <del> "File Link:\t"	""	"text"</del>
>    <del> "File Link:\t\t"	""	"text"</del>

<del>It seems that the string with doubled \t is outdated. Correct?</del>

**Comment by Pierre-de-la-Verre** [comment]
TDL 7.0.1, 31.08.2015

After "Clean Up" I have still these strings in my language file.

    TRANSTEXT 7.0.1.0
    PRIMARY_LANGID 7
    English Text	Translated Text	Item Type
    NEED_TRANSLATION
    "Checkbox"	""	"text"
    "CommentsPopup"	""	"menu"
    "TabCtrl"	""	"menu"
    "TaskContext"	""	"menu"
    "Tasklist (*.tdl, *.xml)"	""	"combobox.1136"
    "TasklistHeader"	""	"menu"
    "Theme Files (*.xml)"	""	"combobox.1136"
    "ToolsDialog"	""	"menu"
    "TreeDragDrop"	""	"menu"

**Comment by abstractspoon** [comment]
@Pierre-de-la-Verre : 

```"Checkbox"  ""  "text"``` is valid. I changed the previously named 'Flag' custom attribute type to 'Checkbox'.

```"combobox.1136"``` is part of the Windows Open File dialog and I don't yet know how to filter this out.

The rest are top-level menu names that are not seen in the UI and ought to be filtered out. Can you confirm that these are not present in your local copy of YourLanguage.csv?

**Comment by abstractspoon** [comment]
@Pierre-de-la-Verre 

> It seems that the string with doubled \t is outdated. Correct?

Correct.

**Comment by abstractspoon** [comment]
@Pierre-de-la-Verre 

I think it might be better if you also look after YourLanguage.csv and I just have responsibility for the text within the app.

**Comment by Pierre-de-la-Verre** [comment]
a) Top Level Menus:
My current YourLanguage.csv is from 20.08.2015 and is from download-package. I just removed the strings and will them remove from GitHub too.

b) look after YourLanguage.csv:
Yes, as far a possible. But I have to ask very often.

c) "new" strings in 7.0.1:
    "\n%s %.2f %c"	""	"text"
    "\n%s %.2f"	""	"text"
    "\n%s %d"	""	"text"
    "\n%s %s (%s)"	""	"text"
    "\n%s %s"	""	"text"

The same strings already exist without "\n". Are the "new ones" additional or a replacement?

**Comment by abstractspoon** [comment]
c) I'm going to try to remove all strings that have no actual text needing translating, but for the time being the strings with the leading '\n' are the correct ones.

**Comment by Pierre-de-la-Verre** [comment]
> ...but for the time being the strings with the leading '\n' are the correct ones.

So it is necessary to modify all languages?

**Comment by abstractspoon** [comment]
This issue was moved to abstractspoon/ToDoList_Issues#65
