### ISSUE TITLE
Request: Shortcuts for custom string

### ISSUE THREAD

**Issue by astrakid** [abstractspoon/ToDoList_Resources#23]
Hi,
I would appreciate to have some shortcuts for entering standard text. e.g. I am using shortcut for entering current date, but it would be great to have some further information added here (my "shortcode" cor commenting tasks).

**Comment by Pierre-de-la-Verre** [comment]
I would recommend Third-party for this:
- Autohotkey AHK http://ahkscript.org/ for this. You can use it for "Shortcut Oneliner Code" up to complex programs. 
- Fast Typing: https://sites.google.com/site/ultratceditors/fast_typing
and many more ..

**Comment by astrakid** [comment]
Thanks for the hints, I understnad the way, but would have liked it to have an "embedded solution". Time and Date could also be managed via ahkscript, but is implemented in todolist.
thanks for your comment,
regards,
astrakid

**Comment by abstractspoon** [comment]
@Andre G : Can you be more specific about the solution you are seeking
together with some clear examples of what you want?

Rgds, .dan.g.

www.abstractspoon.com

**Comment by astrakid** [comment]
sure. I would like to have a shortcut for inserting the date and a custom text, e.g.:
STRG + D => [date] + "comment akid: "
I want to use your existing shortcut and add a custom string. If it is not possible to mix it up it would be a step into the right direction to have another shortcut for custom string, e.g. STRG+E => "comment akid: ", in this case I would need to press STRG+D and STRG+E sequentially to get my desired result. ;-)
regards
astrakid

**Comment by astrakid** [comment]
Just saw, that CTRL+D is timestamp, not date. nevertheless, doesn't matter which shortcut is used...
and "STRG" is "CTRL"... ;-)

**Comment by TonyGravagno** [comment]
I use [PhraseExpress](http://www.phraseexpress.com/) for this. Have used it for many years. It works in all apps, wherever you're typing anything. It's extremely powerful and it's free for personal use.

(IMO) ToDoList doesn't need this built-in when there are a number of free and awesome tools that do so much more than TDL ever could. If you want to start a separate discussion about this in the [TDL Google Group](http://bit.ly/AbstrToDoListGG), I'll be happy to discuss it there.

**Comment by abstractspoon** [comment]
This issue was moved to abstractspoon/ToDoList_Issues#59
