### ISSUE TITLE
AllocByList and AllocToList getting populated with StatusList

### ISSUE THREAD

**Issue by TonyGravagno** [abstractspoon/ToDoList_Resources#9]
Both the Allocated By and Allocated To dropdowns are getting populated with the default Status Categories from the ini. This occurs because when saving the ini it looks like [Preferences\StatusList] is over-writing [Preferences\AllocToList] and [Preferences\AllocByList]. This only seems to occur when the By/To list is empty. If any value is set in this list then the over-write does not occur.

To test:

1. Go to Preferences > Tasks > Defaults > Dynamic Droplists
2. Clear the Allocated By list
3. Put one or two values in the Allocated To list
3. Save and exit the app.
4. Open the app (or the ini file) and note that the By list has been repopulated with status values. Same will happen to To list if cleared.

![Statuses, should be People](http://i198.photobucket.com/albums/aa83/CaptainStarbuck/Screenshots/ToDoList/150711120856_tmpimg_zpsfd1eb7hu.png)

**Comment by abstractspoon** [comment]
Thx Tony, this is an excellent example of a good bug report that I don't have to ask any further questions about.

**Comment by abstractspoon** [comment]
This issue was moved to abstractspoon/ToDoList_Wiki#4
